[custom]
;解决DNS泄露 
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list

ruleset=🇺🇸 美国服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🇺🇸 美国服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🇺🇸 美国服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Disney.list
ruleset=🇯🇵 日本服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixJP.list
ruleset=🇯🇵 日本服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Abema.list
ruleset=🇭🇰 香港服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HKMedia.list
ruleset=🇹🇼 台湾服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TWMedia.list
ruleset=🇰🇷 韩国服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/KRMedia.list
ruleset=🇸🇬 新加坡服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SGMedia.list
ruleset=🇬🇧 英国服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BBC.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港自动`[]🇸🇬 新加坡自动`[]🇯🇵 日本自动`[]🇹🇼 台湾自动`[]🇰🇷 韩国自动`[]🇺🇸 美国自动`[]🇬🇧 英国自动`[]♻️ 自动选择`[]DIRECT`.*

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇭🇰 香港自动`url-test`(HK|Hong|港|Hongkong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡自动`url-test`(SG|Singapore|新加|狮城)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本自动`url-test`(JP|Japan|日本|东京|大阪|埼玉|川崎)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾自动`url-test`(TW|Taiwan|台|新北|台北|台中|桃园)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国自动`url-test`(KR|Korea|韩|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国自动`url-test`(US|United States|美|美国|洛杉矶|硅谷|达拉斯|纽约)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国自动`url-test`(GB|UK|United Kingdom|英|英国|伦敦)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇭🇰 香港`select`(HK|Hong|港|Hongkong|hongkong)
custom_proxy_group=🇸🇬 新加坡`select`(SG|Singapore|新加|狮城)
custom_proxy_group=🇯🇵 日本`select`(JP|Japan|日本|东京|大阪|埼玉|川崎)
custom_proxy_group=🇹🇼 台湾`select`(TW|Taiwan|台|新北|台北|台中|桃园)
custom_proxy_group=🇰🇷 韩国`select`(KR|Korea|韩|首尔|韩|韓)
custom_proxy_group=🇺🇸 美国`select`(US|United States|美|美国|洛杉矶|硅谷|达拉斯|纽约)
custom_proxy_group=🇬🇧 英国`select`(GB|UK|United Kingdom|英|英国|伦敦)

custom_proxy_group=🇺🇸 美国服务`select`[]🇺🇸 美国自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇯🇵 日本服务`select`[]🇯🇵 日本自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇭🇰 香港服务`select`[]🇭🇰 香港自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇹🇼 台湾服务`select`[]🇹🇼 台湾自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇰🇷 韩国服务`select`[]🇰🇷 韩国自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇸🇬 新加坡服务`select`[]🇸🇬 新加坡自动`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🇬🇧 英国服务`select`[]🇬🇧 英国自动`[]🚀 节点选择`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
